package com.docscience.pathfinder.font.driver.cff;

import com.docscience.pathfinder.font.driver.FontException;

/**
 * @author wxin
 *
 */
public class CFFFormatException extends FontException {

    /**
     * Generated by Eclipse 3.2.1
     */
    private static final long serialVersionUID = -409446984341154717L;

    public CFFFormatException(String msg, long pos) {
        super(msg + " at " + pos);
    }
    
    public CFFFormatException(String msg) {
        super(msg);
    }
    
}
