package com.docscience.pathfinder.font.driver.otf;

import com.docscience.pathfinder.font.driver.ttf.TTFHelper;

public final class OTFTypography {
	
	public static final int SCRIPT_TAG_ARABIC = TTFHelper.composeTag("arab");
	public static final int SCRIPT_TAG_ARMENIAN = TTFHelper.composeTag("armn");
	public static final int SCRIPT_TAG_BENGALI = TTFHelper.composeTag("beng");
	public static final int SCRIPT_TAG_BOPOMOFO = TTFHelper.composeTag("bopo");
	public static final int SCRIPT_TAG_BRAILLE = TTFHelper.composeTag("brai");
	public static final int SCRIPT_TAG_BYZANTINE_MUSIC = TTFHelper.composeTag("byzm");
	public static final int SCRIPT_TAG_CANADIAN_SYLLABICS = TTFHelper.composeTag("cans");
	public static final int SCRIPT_TAG_CHEROKEE = TTFHelper.composeTag("cher");
	public static final int SCRIPT_TAG_CJK_IDEOGRAPHIC = TTFHelper.composeTag("hani");
	public static final int SCRIPT_TAG_CYRILLIC = TTFHelper.composeTag("cyrl");
	public static final int SCRIPT_TAG_DEFAULT = TTFHelper.composeTag("DFLT");
	public static final int SCRIPT_TAG_DEVANAGARI = TTFHelper.composeTag("deva");
	public static final int SCRIPT_TAG_ETHIOPIC = TTFHelper.composeTag("ethi");
	public static final int SCRIPT_TAG_GEORGIAN = TTFHelper.composeTag("geor");
	public static final int SCRIPT_TAG_GREEK = TTFHelper.composeTag("grek");
	public static final int SCRIPT_TAG_GUJARATI = TTFHelper.composeTag("gujr");
	public static final int SCRIPT_TAG_GURMUKHI = TTFHelper.composeTag("guru");
	public static final int SCRIPT_TAG_HANGUL_JAMO = TTFHelper.composeTag("jamo");
	public static final int SCRIPT_TAG_HANGUL = TTFHelper.composeTag("hang");
	public static final int SCRIPT_TAG_HEBREW = TTFHelper.composeTag("hebr");
	public static final int SCRIPT_TAG_HIRAGANA = TTFHelper.composeTag("kana");
	public static final int SCRIPT_TAG_KANNADA = TTFHelper.composeTag("knda");
	public static final int SCRIPT_TAG_KATAKANA = TTFHelper.composeTag("kana");
	public static final int SCRIPT_TAG_KHMER = TTFHelper.composeTag("khmr");
	public static final int SCRIPT_TAG_LAO = TTFHelper.composeTag("lao ");
	public static final int SCRIPT_TAG_LATIN = TTFHelper.composeTag("latn");
	public static final int SCRIPT_TAG_MALAYALAM = TTFHelper.composeTag("mlym");
	public static final int SCRIPT_TAG_MONGOLIAN = TTFHelper.composeTag("mong");
	public static final int SCRIPT_TAG_MYANMAR = TTFHelper.composeTag("mymr");
	public static final int SCRIPT_TAG_OGHAM = TTFHelper.composeTag("ogam");
	public static final int SCRIPT_TAG_ORIYA = TTFHelper.composeTag("orya");
	public static final int SCRIPT_TAG_RUNIC = TTFHelper.composeTag("runr");
	public static final int SCRIPT_TAG_SINHALA = TTFHelper.composeTag("sinh");
	public static final int SCRIPT_TAG_SYRIAC = TTFHelper.composeTag("syrc");
	public static final int SCRIPT_TAG_TAMIL = TTFHelper.composeTag("taml");
	public static final int SCRIPT_TAG_TELUGU = TTFHelper.composeTag("telu");
	public static final int SCRIPT_TAG_THAANA = TTFHelper.composeTag("thaa");
	public static final int SCRIPT_TAG_THAI = TTFHelper.composeTag("thai");
	public static final int SCRIPT_TAG_TIBETAN = TTFHelper.composeTag("tibt");
	public static final int SCRIPT_TAG_YI = TTFHelper.composeTag("yi  ");
	
	public static final int LANGUAGE_TAG_ABAZA = TTFHelper.composeTag("ABA ");
	public static final int LANGUAGE_TAG_ABKHAZIAN = TTFHelper.composeTag("ABK ");
	public static final int LANGUAGE_TAG_ADYGHE = TTFHelper.composeTag("ADY ");
	public static final int LANGUAGE_TAG_AFRIKAANS = TTFHelper.composeTag("AFK ");
	public static final int LANGUAGE_TAG_AFAR = TTFHelper.composeTag("AFR ");
	public static final int LANGUAGE_TAG_AGAW = TTFHelper.composeTag("AGW ");
	public static final int LANGUAGE_TAG_ALTAI = TTFHelper.composeTag("ALT ");
	public static final int LANGUAGE_TAG_AMHARIC = TTFHelper.composeTag("AMH ");
	public static final int LANGUAGE_TAG_ARABIC = TTFHelper.composeTag("ARA ");
	public static final int LANGUAGE_TAG_AARI = TTFHelper.composeTag("ARI ");
	public static final int LANGUAGE_TAG_ARAKANESE = TTFHelper.composeTag("ARK ");
	public static final int LANGUAGE_TAG_ASSAMESE = TTFHelper.composeTag("ASM ");
	public static final int LANGUAGE_TAG_ATHAPASKAN = TTFHelper.composeTag("ATH ");
	public static final int LANGUAGE_TAG_AVAR = TTFHelper.composeTag("AVR ");
	public static final int LANGUAGE_TAG_AWADHI = TTFHelper.composeTag("AWA ");
	public static final int LANGUAGE_TAG_AYMARA = TTFHelper.composeTag("AYM ");
	public static final int LANGUAGE_TAG_AZERI = TTFHelper.composeTag("AZE ");
	public static final int LANGUAGE_TAG_BADAGA = TTFHelper.composeTag("BAD ");
	public static final int LANGUAGE_TAG_BAGHELKHANDI = TTFHelper.composeTag("BAG ");
	public static final int LANGUAGE_TAG_BALKAR = TTFHelper.composeTag("BAL ");
	public static final int LANGUAGE_TAG_BAULE = TTFHelper.composeTag("BAU ");
	public static final int LANGUAGE_TAG_BERBER = TTFHelper.composeTag("BBR ");
	public static final int LANGUAGE_TAG_BENCH = TTFHelper.composeTag("BCH ");
	public static final int LANGUAGE_TAG_BIBLE_CREE = TTFHelper.composeTag("BCR ");
	public static final int LANGUAGE_TAG_BELARUSSIAN = TTFHelper.composeTag("BEL ");
	public static final int LANGUAGE_TAG_BEMBA = TTFHelper.composeTag("BEM ");
	public static final int LANGUAGE_TAG_BENGALI = TTFHelper.composeTag("BEN ");
	public static final int LANGUAGE_TAG_BULGARIAN = TTFHelper.composeTag("BGR ");
	public static final int LANGUAGE_TAG_BHILI = TTFHelper.composeTag("BHI ");
	public static final int LANGUAGE_TAG_BHOJPURI = TTFHelper.composeTag("BHO ");
	public static final int LANGUAGE_TAG_BIKOL = TTFHelper.composeTag("BIK ");
	public static final int LANGUAGE_TAG_BILEN = TTFHelper.composeTag("BIL ");
	public static final int LANGUAGE_TAG_BLACKFOOT = TTFHelper.composeTag("BKF ");
	public static final int LANGUAGE_TAG_BALOCHI = TTFHelper.composeTag("BLI ");
	public static final int LANGUAGE_TAG_BALANTE = TTFHelper.composeTag("BLN ");
	public static final int LANGUAGE_TAG_BALTI = TTFHelper.composeTag("BLT ");
	public static final int LANGUAGE_TAG_BAMBARA = TTFHelper.composeTag("BMB ");
	public static final int LANGUAGE_TAG_BAMILEKE = TTFHelper.composeTag("BML ");
	public static final int LANGUAGE_TAG_BRETON = TTFHelper.composeTag("BRE ");
	public static final int LANGUAGE_TAG_BRAHUI = TTFHelper.composeTag("BRH ");
	public static final int LANGUAGE_TAG_BRAJ_BHASHA = TTFHelper.composeTag("BRI ");
	public static final int LANGUAGE_TAG_BURMESE = TTFHelper.composeTag("BRM ");
	public static final int LANGUAGE_TAG_BASHKIR = TTFHelper.composeTag("BSH ");
	public static final int LANGUAGE_TAG_BETI = TTFHelper.composeTag("BTI ");
	public static final int LANGUAGE_TAG_CATALAN = TTFHelper.composeTag("CAT ");
	public static final int LANGUAGE_TAG_CEBUANO = TTFHelper.composeTag("CEB ");
	public static final int LANGUAGE_TAG_CHECHEN = TTFHelper.composeTag("CHE ");
	public static final int LANGUAGE_TAG_CHAHA_GURAGE = TTFHelper.composeTag("CHG ");
	public static final int LANGUAGE_TAG_CHATTISGARHI = TTFHelper.composeTag("CHH ");
	public static final int LANGUAGE_TAG_CHICHEWA = TTFHelper.composeTag("CHI ");
	public static final int LANGUAGE_TAG_CHUKCHI = TTFHelper.composeTag("CHK ");
	public static final int LANGUAGE_TAG_CHIPEWYAN = TTFHelper.composeTag("CHP ");
	public static final int LANGUAGE_TAG_CHEROKEE = TTFHelper.composeTag("CHR ");
	public static final int LANGUAGE_TAG_CHUVASH = TTFHelper.composeTag("CHU ");
	public static final int LANGUAGE_TAG_COMORIAN = TTFHelper.composeTag("CMR ");
	public static final int LANGUAGE_TAG_COPTIC = TTFHelper.composeTag("COP ");
	public static final int LANGUAGE_TAG_CREE = TTFHelper.composeTag("CRE ");
	public static final int LANGUAGE_TAG_CARRIER = TTFHelper.composeTag("CRR ");
	public static final int LANGUAGE_TAG_CRIMEAN_TATAR = TTFHelper.composeTag("CRT ");
	public static final int LANGUAGE_TAG_CHURCH_SLAVONIC = TTFHelper.composeTag("CSL ");
	public static final int LANGUAGE_TAG_CZECH = TTFHelper.composeTag("CSY ");
	public static final int LANGUAGE_TAG_DANISH = TTFHelper.composeTag("DAN ");
	public static final int LANGUAGE_TAG_DARGWA = TTFHelper.composeTag("DAR ");
	public static final int LANGUAGE_TAG_WOODS_CREE = TTFHelper.composeTag("DCR ");
	public static final int LANGUAGE_TAG_GERMAN_STANDARD = TTFHelper.composeTag("DEU ");
	public static final int LANGUAGE_TAG_DOGRI = TTFHelper.composeTag("DGR ");
	public static final int LANGUAGE_TAG_DHIVEHI = TTFHelper.composeTag("DHV ");
	public static final int LANGUAGE_TAG_DJERMA = TTFHelper.composeTag("DJR ");
	public static final int LANGUAGE_TAG_DANGME = TTFHelper.composeTag("DNG ");
	public static final int LANGUAGE_TAG_DINKA = TTFHelper.composeTag("DNK ");
	public static final int LANGUAGE_TAG_DUNGAN = TTFHelper.composeTag("DUN ");
	public static final int LANGUAGE_TAG_DZONGKHA = TTFHelper.composeTag("DZN ");
	public static final int LANGUAGE_TAG_EBIRA = TTFHelper.composeTag("EBI ");
	public static final int LANGUAGE_TAG_EASTERN_CREE = TTFHelper.composeTag("ECR ");
	public static final int LANGUAGE_TAG_EDO = TTFHelper.composeTag("EDO ");
	public static final int LANGUAGE_TAG_EFIK = TTFHelper.composeTag("EFI ");
	public static final int LANGUAGE_TAG_GREEK = TTFHelper.composeTag("ELL ");
	public static final int LANGUAGE_TAG_ENGLISH = TTFHelper.composeTag("ENG ");
	public static final int LANGUAGE_TAG_ERZYA = TTFHelper.composeTag("ERZ ");
	public static final int LANGUAGE_TAG_SPANISH = TTFHelper.composeTag("ESP ");
	public static final int LANGUAGE_TAG_ESTONIAN = TTFHelper.composeTag("ETI ");
	public static final int LANGUAGE_TAG_BASQUE = TTFHelper.composeTag("EUQ ");
	public static final int LANGUAGE_TAG_EVENKI = TTFHelper.composeTag("EVK ");
	public static final int LANGUAGE_TAG_EVEN = TTFHelper.composeTag("EVN ");
	public static final int LANGUAGE_TAG_EWE = TTFHelper.composeTag("EWE ");
	public static final int LANGUAGE_TAG_FRENCH_ANTILLEAN = TTFHelper.composeTag("FAN ");
	public static final int LANGUAGE_TAG_FARSI = TTFHelper.composeTag("FAR ");
	public static final int LANGUAGE_TAG_FINNISH = TTFHelper.composeTag("FIN ");
	public static final int LANGUAGE_TAG_FIJIAN = TTFHelper.composeTag("FJI ");
	public static final int LANGUAGE_TAG_FLEMISH = TTFHelper.composeTag("FLE ");
	public static final int LANGUAGE_TAG_FOREST_NENETS = TTFHelper.composeTag("FNE ");
	public static final int LANGUAGE_TAG_FON = TTFHelper.composeTag("FON ");
	public static final int LANGUAGE_TAG_FAROESE = TTFHelper.composeTag("FOS ");
	public static final int LANGUAGE_TAG_FRENCH_STANDARD = TTFHelper.composeTag("FRA ");
	public static final int LANGUAGE_TAG_FRISIAN = TTFHelper.composeTag("FRI ");
	public static final int LANGUAGE_TAG_FRIULIAN = TTFHelper.composeTag("FRL ");
	public static final int LANGUAGE_TAG_FUTA = TTFHelper.composeTag("FTA ");
	public static final int LANGUAGE_TAG_FULANI = TTFHelper.composeTag("FUL ");
	public static final int LANGUAGE_TAG_GA = TTFHelper.composeTag("GAD ");
	public static final int LANGUAGE_TAG_GAELIC = TTFHelper.composeTag("GAE ");
	public static final int LANGUAGE_TAG_GAGAUZ = TTFHelper.composeTag("GAG ");
	public static final int LANGUAGE_TAG_GALICIAN = TTFHelper.composeTag("GAL ");
	public static final int LANGUAGE_TAG_GARSHUNI = TTFHelper.composeTag("GAR ");
	public static final int LANGUAGE_TAG_GARHWALI = TTFHelper.composeTag("GAW ");
	public static final int LANGUAGE_TAG_GE_EZ = TTFHelper.composeTag("GEZ ");
	public static final int LANGUAGE_TAG_GILYAK = TTFHelper.composeTag("GIL ");
	public static final int LANGUAGE_TAG_GUMUZ = TTFHelper.composeTag("GMZ ");
	public static final int LANGUAGE_TAG_GONDI = TTFHelper.composeTag("GON ");
	public static final int LANGUAGE_TAG_GREENLANDIC = TTFHelper.composeTag("GRN ");
	public static final int LANGUAGE_TAG_GARO = TTFHelper.composeTag("GRO ");
	public static final int LANGUAGE_TAG_GUARANI = TTFHelper.composeTag("GUA ");
	public static final int LANGUAGE_TAG_GUJARATI = TTFHelper.composeTag("GUJ ");
	public static final int LANGUAGE_TAG_HAITIAN = TTFHelper.composeTag("HAI ");
	public static final int LANGUAGE_TAG_HALAM = TTFHelper.composeTag("HAL ");
	public static final int LANGUAGE_TAG_HARAUTI = TTFHelper.composeTag("HAR ");
	public static final int LANGUAGE_TAG_HAUSA = TTFHelper.composeTag("HAU ");
	public static final int LANGUAGE_TAG_HAWAIIN = TTFHelper.composeTag("HAW ");
	public static final int LANGUAGE_TAG_HAMMER_BANNA = TTFHelper.composeTag("HBN ");
	public static final int LANGUAGE_TAG_HILIGAYNON = TTFHelper.composeTag("HIL ");
	public static final int LANGUAGE_TAG_HINDI = TTFHelper.composeTag("HIN ");
	public static final int LANGUAGE_TAG_HIGH_MARI = TTFHelper.composeTag("HMA ");
	public static final int LANGUAGE_TAG_HINDKO = TTFHelper.composeTag("HND ");
	public static final int LANGUAGE_TAG_HO = TTFHelper.composeTag("HO  ");
	public static final int LANGUAGE_TAG_HARARI = TTFHelper.composeTag("HRI ");
	public static final int LANGUAGE_TAG_CROATIAN = TTFHelper.composeTag("HRV ");
	public static final int LANGUAGE_TAG_HUNGARIAN = TTFHelper.composeTag("HUN ");
	public static final int LANGUAGE_TAG_ARMENIAN = TTFHelper.composeTag("HYE ");
	public static final int LANGUAGE_TAG_IGBO = TTFHelper.composeTag("IBO ");
	public static final int LANGUAGE_TAG_IJO = TTFHelper.composeTag("IJO ");
	public static final int LANGUAGE_TAG_ILOKANO = TTFHelper.composeTag("ILO ");
	public static final int LANGUAGE_TAG_INDONESIAN = TTFHelper.composeTag("IND ");
	public static final int LANGUAGE_TAG_INGUSH = TTFHelper.composeTag("ING ");
	public static final int LANGUAGE_TAG_INUKTITUT = TTFHelper.composeTag("INU ");
	public static final int LANGUAGE_TAG_IRISH = TTFHelper.composeTag("IRI ");
	public static final int LANGUAGE_TAG_IRISH_TRADITIONAL = TTFHelper.composeTag("IRT ");
	public static final int LANGUAGE_TAG_ICELANDIC = TTFHelper.composeTag("ISL ");
	public static final int LANGUAGE_TAG_INARI_SAMI = TTFHelper.composeTag("ISM ");
	public static final int LANGUAGE_TAG_ITALIAN = TTFHelper.composeTag("ITA ");
	public static final int LANGUAGE_TAG_HEBREW = TTFHelper.composeTag("IWR ");
	public static final int LANGUAGE_TAG_JAVANESE = TTFHelper.composeTag("JAV ");
	public static final int LANGUAGE_TAG_YIDDISH = TTFHelper.composeTag("JII ");
	public static final int LANGUAGE_TAG_JAPANESE = TTFHelper.composeTag("JAN ");
	public static final int LANGUAGE_TAG_JUDEZMO = TTFHelper.composeTag("JUD ");
	public static final int LANGUAGE_TAG_JULA = TTFHelper.composeTag("JUL ");
	public static final int LANGUAGE_TAG_KABARDIAN = TTFHelper.composeTag("KAB ");
	public static final int LANGUAGE_TAG_KACHCHI = TTFHelper.composeTag("KAC ");
	public static final int LANGUAGE_TAG_KALENJIN = TTFHelper.composeTag("KAL ");
	public static final int LANGUAGE_TAG_KANNADA = TTFHelper.composeTag("KAN ");
	public static final int LANGUAGE_TAG_KARACHAY = TTFHelper.composeTag("KAR ");
	public static final int LANGUAGE_TAG_GEORGIAN = TTFHelper.composeTag("KAT ");
	public static final int LANGUAGE_TAG_KAZAKH = TTFHelper.composeTag("KAZ ");
	public static final int LANGUAGE_TAG_KEBENA = TTFHelper.composeTag("KEB ");
	public static final int LANGUAGE_TAG_KHUTSURI_GEORGIAN = TTFHelper.composeTag("KGE ");
	public static final int LANGUAGE_TAG_KHAKASS = TTFHelper.composeTag("KHA ");
	public static final int LANGUAGE_TAG_KHANTY_KAZIM = TTFHelper.composeTag("KHK ");
	public static final int LANGUAGE_TAG_KHMER = TTFHelper.composeTag("KHM ");
	public static final int LANGUAGE_TAG_KHANTY_SHURISHKAR = TTFHelper.composeTag("KHS ");
	public static final int LANGUAGE_TAG_KHANTY_VAKHI = TTFHelper.composeTag("KHV ");
	public static final int LANGUAGE_TAG_KHOWAR = TTFHelper.composeTag("KHW ");
	public static final int LANGUAGE_TAG_KIKUYU = TTFHelper.composeTag("KIK ");
	public static final int LANGUAGE_TAG_KIRGHIZ = TTFHelper.composeTag("KIR ");
	public static final int LANGUAGE_TAG_KISII = TTFHelper.composeTag("KIS ");
	public static final int LANGUAGE_TAG_KOKNI = TTFHelper.composeTag("KKN ");
	public static final int LANGUAGE_TAG_KALMYK = TTFHelper.composeTag("KLM ");
	public static final int LANGUAGE_TAG_KAMBA = TTFHelper.composeTag("KMB ");
	public static final int LANGUAGE_TAG_KUMAONI = TTFHelper.composeTag("KMN ");
	public static final int LANGUAGE_TAG_KOMO = TTFHelper.composeTag("KMO ");
	public static final int LANGUAGE_TAG_KOMSO = TTFHelper.composeTag("KMS ");
	public static final int LANGUAGE_TAG_KANURI = TTFHelper.composeTag("KNR ");
	public static final int LANGUAGE_TAG_KODAGU = TTFHelper.composeTag("KOD ");
	public static final int LANGUAGE_TAG_KONKANI = TTFHelper.composeTag("KOK ");
	public static final int LANGUAGE_TAG_KIKONGO = TTFHelper.composeTag("KON ");
	public static final int LANGUAGE_TAG_KOMI_PERMYAK = TTFHelper.composeTag("KOP ");
	public static final int LANGUAGE_TAG_KOREAN = TTFHelper.composeTag("KOR ");
	public static final int LANGUAGE_TAG_KOMI_ZYRIAN = TTFHelper.composeTag("KOZ ");
	public static final int LANGUAGE_TAG_KPELLE = TTFHelper.composeTag("KPL ");
	public static final int LANGUAGE_TAG_KRIO = TTFHelper.composeTag("KRI ");
	public static final int LANGUAGE_TAG_KARAKALPAK = TTFHelper.composeTag("KRK ");
	public static final int LANGUAGE_TAG_KARELIAN = TTFHelper.composeTag("KRL ");
	public static final int LANGUAGE_TAG_KARAIM = TTFHelper.composeTag("KRM ");
	public static final int LANGUAGE_TAG_KAREN = TTFHelper.composeTag("KRN ");
	public static final int LANGUAGE_TAG_KOORETE = TTFHelper.composeTag("KRT ");
	public static final int LANGUAGE_TAG_KASHMIRI = TTFHelper.composeTag("KSH ");
	public static final int LANGUAGE_TAG_KHASI = TTFHelper.composeTag("KSI ");
	public static final int LANGUAGE_TAG_KILDIN_SAMI = TTFHelper.composeTag("KSM ");
	public static final int LANGUAGE_TAG_KUI = TTFHelper.composeTag("KUI ");
	public static final int LANGUAGE_TAG_KULVI = TTFHelper.composeTag("KUL ");
	public static final int LANGUAGE_TAG_KUMYK = TTFHelper.composeTag("KUM ");
	public static final int LANGUAGE_TAG_KURDISH = TTFHelper.composeTag("KUR ");
	public static final int LANGUAGE_TAG_KURUKH = TTFHelper.composeTag("KUU ");
	public static final int LANGUAGE_TAG_KUY = TTFHelper.composeTag("KUY ");
	public static final int LANGUAGE_TAG_KORYAK = TTFHelper.composeTag("KYK ");
	public static final int LANGUAGE_TAG_LADIN = TTFHelper.composeTag("LAD ");
	public static final int LANGUAGE_TAG_LAHULI = TTFHelper.composeTag("LAH ");
	public static final int LANGUAGE_TAG_LAK = TTFHelper.composeTag("LAK ");
	public static final int LANGUAGE_TAG_LAMBANI = TTFHelper.composeTag("LAM ");
	public static final int LANGUAGE_TAG_LAO = TTFHelper.composeTag("LAO ");
	public static final int LANGUAGE_TAG_LATIN = TTFHelper.composeTag("LAT ");
	public static final int LANGUAGE_TAG_LAZ = TTFHelper.composeTag("LAZ ");
	public static final int LANGUAGE_TAG_L_CREE = TTFHelper.composeTag("LCR ");
	public static final int LANGUAGE_TAG_LADAKHI = TTFHelper.composeTag("LDK ");
	public static final int LANGUAGE_TAG_LEZGI = TTFHelper.composeTag("LEZ ");
	public static final int LANGUAGE_TAG_LINGALA = TTFHelper.composeTag("LIN ");
	public static final int LANGUAGE_TAG_LOW_MARI = TTFHelper.composeTag("LMA ");
	public static final int LANGUAGE_TAG_LIMBU = TTFHelper.composeTag("LMB ");
	public static final int LANGUAGE_TAG_LOMWE = TTFHelper.composeTag("LMW ");
	public static final int LANGUAGE_TAG_LOWER_SORBIAN = TTFHelper.composeTag("LSB ");
	public static final int LANGUAGE_TAG_LULE_SAMI = TTFHelper.composeTag("LSM ");
	public static final int LANGUAGE_TAG_LITHUANIAN = TTFHelper.composeTag("LTH ");
	public static final int LANGUAGE_TAG_LUBA = TTFHelper.composeTag("LUB ");
	public static final int LANGUAGE_TAG_LUGANDA = TTFHelper.composeTag("LUG ");
	public static final int LANGUAGE_TAG_LUHYA = TTFHelper.composeTag("LUH ");
	public static final int LANGUAGE_TAG_LUO = TTFHelper.composeTag("LUO ");
	public static final int LANGUAGE_TAG_LATVIAN = TTFHelper.composeTag("LVI ");
	public static final int LANGUAGE_TAG_MAJANG = TTFHelper.composeTag("MAJ ");
	public static final int LANGUAGE_TAG_MAKUA = TTFHelper.composeTag("MAK ");
	public static final int LANGUAGE_TAG_MALAYALAM_TRADITIONAL = TTFHelper.composeTag("MAL ");
	public static final int LANGUAGE_TAG_MANSI = TTFHelper.composeTag("MAN ");
	public static final int LANGUAGE_TAG_MARATHI = TTFHelper.composeTag("MAR ");
	public static final int LANGUAGE_TAG_MARWARI = TTFHelper.composeTag("MAW ");
	public static final int LANGUAGE_TAG_MBUNDU = TTFHelper.composeTag("MBN ");
	public static final int LANGUAGE_TAG_MANCHU = TTFHelper.composeTag("MCH ");
	public static final int LANGUAGE_TAG_MOOSE_CREE = TTFHelper.composeTag("MCR ");
	public static final int LANGUAGE_TAG_MENDE = TTFHelper.composeTag("MDE ");
	public static final int LANGUAGE_TAG_ME_EN = TTFHelper.composeTag("MEN ");
	public static final int LANGUAGE_TAG_MIZO = TTFHelper.composeTag("MIZ ");
	public static final int LANGUAGE_TAG_MACEDONIAN = TTFHelper.composeTag("MKD ");
	public static final int LANGUAGE_TAG_MALE = TTFHelper.composeTag("MLE ");
	public static final int LANGUAGE_TAG_MALAGASY = TTFHelper.composeTag("MLG ");
	public static final int LANGUAGE_TAG_MALINKE = TTFHelper.composeTag("MLN ");
	public static final int LANGUAGE_TAG_MALAYALAM_REFORMED = TTFHelper.composeTag("MLR ");
	public static final int LANGUAGE_TAG_MALAY = TTFHelper.composeTag("MLY ");
	public static final int LANGUAGE_TAG_MANDINKA = TTFHelper.composeTag("MND ");
	public static final int LANGUAGE_TAG_MONGOLIAN = TTFHelper.composeTag("MNG ");
	public static final int LANGUAGE_TAG_MANIPURI = TTFHelper.composeTag("MNI ");
	public static final int LANGUAGE_TAG_MANINKA = TTFHelper.composeTag("MNK ");
	public static final int LANGUAGE_TAG_MANX_GAELIC = TTFHelper.composeTag("MNX ");
	public static final int LANGUAGE_TAG_MOKSHA = TTFHelper.composeTag("MOK ");
	public static final int LANGUAGE_TAG_MOLDAVIAN = TTFHelper.composeTag("MOL ");
	public static final int LANGUAGE_TAG_MON = TTFHelper.composeTag("MON ");
	public static final int LANGUAGE_TAG_MOROCCAN = TTFHelper.composeTag("MOR ");
	public static final int LANGUAGE_TAG_MAORI = TTFHelper.composeTag("MRI ");
	public static final int LANGUAGE_TAG_MAITHILI = TTFHelper.composeTag("MTH ");
	public static final int LANGUAGE_TAG_MALTESE = TTFHelper.composeTag("MTS ");
	public static final int LANGUAGE_TAG_MUNDARI = TTFHelper.composeTag("MUN ");
	public static final int LANGUAGE_TAG_NAGA_ASSAMESE = TTFHelper.composeTag("NAG ");
	public static final int LANGUAGE_TAG_NANAI = TTFHelper.composeTag("NAN ");
	public static final int LANGUAGE_TAG_NASKAPI = TTFHelper.composeTag("NAS ");
	public static final int LANGUAGE_TAG_N_CREE = TTFHelper.composeTag("NCR ");
	public static final int LANGUAGE_TAG_NDEBELE = TTFHelper.composeTag("NDB ");
	public static final int LANGUAGE_TAG_NDONGA = TTFHelper.composeTag("NDG ");
	public static final int LANGUAGE_TAG_NEPALI = TTFHelper.composeTag("NEP ");
	public static final int LANGUAGE_TAG_NEWARI = TTFHelper.composeTag("NEW ");
	public static final int LANGUAGE_TAG_NORWAY_HOUSE_CREE = TTFHelper.composeTag("NHC ");
	public static final int LANGUAGE_TAG_NISI = TTFHelper.composeTag("NIS ");
	public static final int LANGUAGE_TAG_NIUEAN = TTFHelper.composeTag("NIU ");
	public static final int LANGUAGE_TAG_NKOLE = TTFHelper.composeTag("NKL ");
	public static final int LANGUAGE_TAG_DUTCH = TTFHelper.composeTag("NLD ");
	public static final int LANGUAGE_TAG_NOGAI = TTFHelper.composeTag("NOG ");
	public static final int LANGUAGE_TAG_NORWEGIAN = TTFHelper.composeTag("NOR ");
	public static final int LANGUAGE_TAG_NORTHERN_SAMI = TTFHelper.composeTag("NSM ");
	public static final int LANGUAGE_TAG_NORTHERN_TAI = TTFHelper.composeTag("NTA ");
	public static final int LANGUAGE_TAG_ESPERANTO = TTFHelper.composeTag("NTO ");
	public static final int LANGUAGE_TAG_NYNORSK = TTFHelper.composeTag("NYN ");
	public static final int LANGUAGE_TAG_OJI_CREE = TTFHelper.composeTag("OCR ");
	public static final int LANGUAGE_TAG_OJIBWAY = TTFHelper.composeTag("OJB ");
	public static final int LANGUAGE_TAG_ORIYA = TTFHelper.composeTag("ORI ");
	public static final int LANGUAGE_TAG_OROMO = TTFHelper.composeTag("ORO ");
	public static final int LANGUAGE_TAG_OSSETIAN = TTFHelper.composeTag("OSS ");
	public static final int LANGUAGE_TAG_PALESTINIAN_ARAMAIC = TTFHelper.composeTag("PAA ");
	public static final int LANGUAGE_TAG_PALI = TTFHelper.composeTag("PAL ");
	public static final int LANGUAGE_TAG_PUNJABI = TTFHelper.composeTag("PAN ");
	public static final int LANGUAGE_TAG_PALPA = TTFHelper.composeTag("PAP ");
	public static final int LANGUAGE_TAG_PASHTO = TTFHelper.composeTag("PAS ");
	public static final int LANGUAGE_TAG_POLYTONIC_GREEK = TTFHelper.composeTag("PGR ");
	public static final int LANGUAGE_TAG_PILIPINO = TTFHelper.composeTag("PIL ");
	public static final int LANGUAGE_TAG_PALAUNG = TTFHelper.composeTag("PLG ");
	public static final int LANGUAGE_TAG_POLISH = TTFHelper.composeTag("PLK ");
	public static final int LANGUAGE_TAG_PROVENCAL = TTFHelper.composeTag("PRO ");
	public static final int LANGUAGE_TAG_PORTUGUESE = TTFHelper.composeTag("PTG ");
	public static final int LANGUAGE_TAG_CHIN = TTFHelper.composeTag("QIN ");
	public static final int LANGUAGE_TAG_RAJASTHANI = TTFHelper.composeTag("RAJ ");
	public static final int LANGUAGE_TAG_R_CREE = TTFHelper.composeTag("RCR ");
	public static final int LANGUAGE_TAG_RUSSIAN_BURIAT = TTFHelper.composeTag("RBU ");
	public static final int LANGUAGE_TAG_RIANG = TTFHelper.composeTag("RIA ");
	public static final int LANGUAGE_TAG_RHAETO_ROMANIC = TTFHelper.composeTag("RMS ");
	public static final int LANGUAGE_TAG_ROMANIAN = TTFHelper.composeTag("ROM ");
	public static final int LANGUAGE_TAG_ROMANY = TTFHelper.composeTag("ROY ");
	public static final int LANGUAGE_TAG_RUSYN = TTFHelper.composeTag("RSY ");
	public static final int LANGUAGE_TAG_RUANDA = TTFHelper.composeTag("RUA ");
	public static final int LANGUAGE_TAG_RUSSIAN = TTFHelper.composeTag("RUS ");
	public static final int LANGUAGE_TAG_SADRI = TTFHelper.composeTag("SAD ");
	public static final int LANGUAGE_TAG_SANSKRIT = TTFHelper.composeTag("SAN ");
	public static final int LANGUAGE_TAG_SANTALI = TTFHelper.composeTag("SAT ");
	public static final int LANGUAGE_TAG_SAYISI = TTFHelper.composeTag("SAY ");
	public static final int LANGUAGE_TAG_SEKOTA = TTFHelper.composeTag("SEK ");
	public static final int LANGUAGE_TAG_SELKUP = TTFHelper.composeTag("SEL ");
	public static final int LANGUAGE_TAG_SANGO = TTFHelper.composeTag("SGO ");
	public static final int LANGUAGE_TAG_SHAN = TTFHelper.composeTag("SHN ");
	public static final int LANGUAGE_TAG_SIBE = TTFHelper.composeTag("SIB ");
	public static final int LANGUAGE_TAG_SIDAMO = TTFHelper.composeTag("SID ");
	public static final int LANGUAGE_TAG_SILTE_GURAGE = TTFHelper.composeTag("SIG ");
	public static final int LANGUAGE_TAG_SKOLT_SAMI = TTFHelper.composeTag("SKS ");
	public static final int LANGUAGE_TAG_SLOVAK = TTFHelper.composeTag("SKY ");
	public static final int LANGUAGE_TAG_SLAVEY = TTFHelper.composeTag("SLA ");
	public static final int LANGUAGE_TAG_SLOVENIAN = TTFHelper.composeTag("SLV ");
	public static final int LANGUAGE_TAG_SOMALI = TTFHelper.composeTag("SML ");
	public static final int LANGUAGE_TAG_SAMOAN = TTFHelper.composeTag("SMO ");
	public static final int LANGUAGE_TAG_SENA = TTFHelper.composeTag("SNA ");
	public static final int LANGUAGE_TAG_SINDHI = TTFHelper.composeTag("SND ");
	public static final int LANGUAGE_TAG_SINHALESE = TTFHelper.composeTag("SNH ");
	public static final int LANGUAGE_TAG_SONINKE = TTFHelper.composeTag("SNK ");
	public static final int LANGUAGE_TAG_SODO_GURAGE = TTFHelper.composeTag("SOG ");
	public static final int LANGUAGE_TAG_SOTHO = TTFHelper.composeTag("SOT ");
	public static final int LANGUAGE_TAG_ALBANIAN = TTFHelper.composeTag("SQI ");
	public static final int LANGUAGE_TAG_SERBIAN = TTFHelper.composeTag("SRB ");
	public static final int LANGUAGE_TAG_SARAIKI = TTFHelper.composeTag("SRK ");
	public static final int LANGUAGE_TAG_SERER = TTFHelper.composeTag("SRR ");
	public static final int LANGUAGE_TAG_SOUTH_SLAVEY = TTFHelper.composeTag("SSL ");
	public static final int LANGUAGE_TAG_SOUTHERN_SAMI = TTFHelper.composeTag("SSM ");
	public static final int LANGUAGE_TAG_SURI = TTFHelper.composeTag("SUR ");
	public static final int LANGUAGE_TAG_SVAN = TTFHelper.composeTag("SVA ");
	public static final int LANGUAGE_TAG_SWEDISH = TTFHelper.composeTag("SVE ");
	public static final int LANGUAGE_TAG_SWADAYA_ARAMAIC = TTFHelper.composeTag("SWA ");
	public static final int LANGUAGE_TAG_SWAHILI = TTFHelper.composeTag("SWK ");
	public static final int LANGUAGE_TAG_SWAZI = TTFHelper.composeTag("SWZ ");
	public static final int LANGUAGE_TAG_SUTU = TTFHelper.composeTag("SXT ");
	public static final int LANGUAGE_TAG_SYRIAC = TTFHelper.composeTag("SYR ");
	public static final int LANGUAGE_TAG_TABASARAN = TTFHelper.composeTag("TAB ");
	public static final int LANGUAGE_TAG_TAJIKI = TTFHelper.composeTag("TAJ ");
	public static final int LANGUAGE_TAG_TAMIL = TTFHelper.composeTag("TAM ");
	public static final int LANGUAGE_TAG_TATAR = TTFHelper.composeTag("TAT ");
	public static final int LANGUAGE_TAG_TH_CREE = TTFHelper.composeTag("TCR ");
	public static final int LANGUAGE_TAG_TELUGU = TTFHelper.composeTag("TEL ");
	public static final int LANGUAGE_TAG_TONGAN = TTFHelper.composeTag("TGN ");
	public static final int LANGUAGE_TAG_TIGRE = TTFHelper.composeTag("TGR ");
	public static final int LANGUAGE_TAG_TIGRINYA = TTFHelper.composeTag("TGY ");
	public static final int LANGUAGE_TAG_THAI = TTFHelper.composeTag("THA ");
	public static final int LANGUAGE_TAG_TAHITIAN = TTFHelper.composeTag("THT ");
	public static final int LANGUAGE_TAG_TIBETAN = TTFHelper.composeTag("TIB ");
	public static final int LANGUAGE_TAG_TURKMEN = TTFHelper.composeTag("TKM ");
	public static final int LANGUAGE_TAG_TEMNE = TTFHelper.composeTag("TMN ");
	public static final int LANGUAGE_TAG_TSWANA = TTFHelper.composeTag("TNA ");
	public static final int LANGUAGE_TAG_TUNDRA_NENETS = TTFHelper.composeTag("TNE ");
	public static final int LANGUAGE_TAG_TONGA = TTFHelper.composeTag("TNG ");
	public static final int LANGUAGE_TAG_TODO = TTFHelper.composeTag("TOD ");
	public static final int LANGUAGE_TAG_TURKISH = TTFHelper.composeTag("TRK ");
	public static final int LANGUAGE_TAG_TSONGA = TTFHelper.composeTag("TSG ");
	public static final int LANGUAGE_TAG_TUROYO_ARAMAIC = TTFHelper.composeTag("TUA ");
	public static final int LANGUAGE_TAG_TULU = TTFHelper.composeTag("TUL ");
	public static final int LANGUAGE_TAG_TUVIN = TTFHelper.composeTag("TUV ");
	public static final int LANGUAGE_TAG_TWI = TTFHelper.composeTag("TWI ");
	public static final int LANGUAGE_TAG_UDMURT = TTFHelper.composeTag("UDM ");
	public static final int LANGUAGE_TAG_UKRAINIAN = TTFHelper.composeTag("UKR ");
	public static final int LANGUAGE_TAG_URDU = TTFHelper.composeTag("URD ");
	public static final int LANGUAGE_TAG_UPPER_SORBIAN = TTFHelper.composeTag("USB ");
	public static final int LANGUAGE_TAG_UYGHUR = TTFHelper.composeTag("UYG ");
	public static final int LANGUAGE_TAG_UZBEK = TTFHelper.composeTag("UZB ");
	public static final int LANGUAGE_TAG_VENDA = TTFHelper.composeTag("VEN ");
	public static final int LANGUAGE_TAG_VIETNAMESE = TTFHelper.composeTag("VIT ");
	public static final int LANGUAGE_TAG_WA = TTFHelper.composeTag("WA  ");
	public static final int LANGUAGE_TAG_WAGDI = TTFHelper.composeTag("WAG ");
	public static final int LANGUAGE_TAG_WEST_CREE = TTFHelper.composeTag("WCR ");
	public static final int LANGUAGE_TAG_WELSH = TTFHelper.composeTag("WEL ");
	public static final int LANGUAGE_TAG_WOLOF = TTFHelper.composeTag("WLF ");
	public static final int LANGUAGE_TAG_XHOSA = TTFHelper.composeTag("XHS ");
	public static final int LANGUAGE_TAG_YAKUT = TTFHelper.composeTag("YAK ");
	public static final int LANGUAGE_TAG_YORUBA = TTFHelper.composeTag("YBA ");
	public static final int LANGUAGE_TAG_Y_CREE = TTFHelper.composeTag("YCR ");
	public static final int LANGUAGE_TAG_YI_CLASSIC = TTFHelper.composeTag("YIC ");
	public static final int LANGUAGE_TAG_YI_MODERN = TTFHelper.composeTag("YIM ");
	public static final int LANGUAGE_TAG_CHINESE_PHONETIC = TTFHelper.composeTag("ZHP ");
	public static final int LANGUAGE_TAG_CHINESE_SIMPLIFIED = TTFHelper.composeTag("ZHS ");
	public static final int LANGUAGE_TAG_CHINESE_TRADITIONAL = TTFHelper.composeTag("ZHT ");
	public static final int LANGUAGE_TAG_ZANDE = TTFHelper.composeTag("ZND ");
	public static final int LANGUAGE_TAG_ZULU = TTFHelper.composeTag("ZUL ");
	
	public static final int FEATURE_TAG_AALT = TTFHelper.composeTag("aalt");//Access All Alternates
	public static final int FEATURE_TAG_ABVF = TTFHelper.composeTag("abvf");//Above-base Forms
	public static final int FEATURE_TAG_ABVM = TTFHelper.composeTag("abvm");//Above-base Mark Positioning
	public static final int FEATURE_TAG_ABVS = TTFHelper.composeTag("abvs");//Above-base Substitutions
	public static final int FEATURE_TAG_AFRC = TTFHelper.composeTag("afrc");//Alternative Fractions
	public static final int FEATURE_TAG_AKHN = TTFHelper.composeTag("akhn");//Akhands
	public static final int FEATURE_TAG_BLWF = TTFHelper.composeTag("blwf");//Below-base Forms
	public static final int FEATURE_TAG_BLWM = TTFHelper.composeTag("blwm");//Below-base Mark Positioning
	public static final int FEATURE_TAG_BLWS = TTFHelper.composeTag("blws");//Below-base Substitutions
	public static final int FEATURE_TAG_CALT = TTFHelper.composeTag("calt");//Contextual Alternates
	public static final int FEATURE_TAG_CASE = TTFHelper.composeTag("case");//Case-Sensitive Forms
	public static final int FEATURE_TAG_CCMP = TTFHelper.composeTag("ccmp");//Glyph Composition / Decomposition
	public static final int FEATURE_TAG_CFAR = TTFHelper.composeTag("cfar");//Conjunct Form After Ro
	public static final int FEATURE_TAG_CJCT = TTFHelper.composeTag("cjct");//Conjunct Forms
	public static final int FEATURE_TAG_CLIG = TTFHelper.composeTag("clig");//Contextual Ligatures
	public static final int FEATURE_TAG_CPCT = TTFHelper.composeTag("cpct");//Centered CJK Punctuation
	public static final int FEATURE_TAG_CPSP = TTFHelper.composeTag("cpsp");//Capital Spacing
	public static final int FEATURE_TAG_CSWH = TTFHelper.composeTag("cswh");//Contextual Swash
	public static final int FEATURE_TAG_CURS = TTFHelper.composeTag("curs");//Cursive Positioning
	public static final int FEATURE_TAG_C2PC = TTFHelper.composeTag("c2pc");//Petite Capitals From Capitals
	public static final int FEATURE_TAG_C2SC = TTFHelper.composeTag("c2sc");//Small Capitals From Capitals
	public static final int FEATURE_TAG_DIST = TTFHelper.composeTag("dist");//Distances
	public static final int FEATURE_TAG_DLIG = TTFHelper.composeTag("dlig");//Discretionary Ligatures
	public static final int FEATURE_TAG_DNOM = TTFHelper.composeTag("dnom");//Denominators
	public static final int FEATURE_TAG_EXPT = TTFHelper.composeTag("expt");//Expert Forms
	public static final int FEATURE_TAG_FALT = TTFHelper.composeTag("falt");//Final Glyph on Line Alternates
	public static final int FEATURE_TAG_FIN2 = TTFHelper.composeTag("fin2");//Terminal Forms #2
	public static final int FEATURE_TAG_FIN3 = TTFHelper.composeTag("fin3");//Terminal Forms #3
	public static final int FEATURE_TAG_FINA = TTFHelper.composeTag("fina");//Terminal Forms
	public static final int FEATURE_TAG_FRAC = TTFHelper.composeTag("frac");//Fractions
	public static final int FEATURE_TAG_FWID = TTFHelper.composeTag("fwid");//Full Widths
	public static final int FEATURE_TAG_HALF = TTFHelper.composeTag("half");//Half Forms
	public static final int FEATURE_TAG_HALN = TTFHelper.composeTag("haln");//Halant Forms
	public static final int FEATURE_TAG_HALT = TTFHelper.composeTag("halt");//Alternate Half Widths
	public static final int FEATURE_TAG_HIST = TTFHelper.composeTag("hist");//Historical Forms
	public static final int FEATURE_TAG_HKNA = TTFHelper.composeTag("hkna");//Horizontal Kana Alternates
	public static final int FEATURE_TAG_HLIG = TTFHelper.composeTag("hlig");//Historical Ligatures
	public static final int FEATURE_TAG_HNGL = TTFHelper.composeTag("hngl");//Hangul
	public static final int FEATURE_TAG_HOJO = TTFHelper.composeTag("hojo");//Hojo Kanji Forms (JIS X 0212-1990 Kanji Forms)
	public static final int FEATURE_TAG_HWID = TTFHelper.composeTag("hwid");//Half Widths
	public static final int FEATURE_TAG_INIT = TTFHelper.composeTag("init");//Initial Forms
	public static final int FEATURE_TAG_ISOL = TTFHelper.composeTag("isol");//Isolated Forms
	public static final int FEATURE_TAG_ITAL = TTFHelper.composeTag("ital");//Italics
	public static final int FEATURE_TAG_JALT = TTFHelper.composeTag("jalt");//Justification Alternates
	public static final int FEATURE_TAG_JP78 = TTFHelper.composeTag("jp78");//JIS78 Forms
	public static final int FEATURE_TAG_JP83 = TTFHelper.composeTag("jp83");//JIS83 Forms
	public static final int FEATURE_TAG_JP90 = TTFHelper.composeTag("jp90");//JIS90 Forms
	public static final int FEATURE_TAG_JP04 = TTFHelper.composeTag("jp04");//JIS2004 Forms
	public static final int FEATURE_TAG_KERN = TTFHelper.composeTag("kern");//Kerning
	public static final int FEATURE_TAG_LFBD = TTFHelper.composeTag("lfbd");//Left Bounds
	public static final int FEATURE_TAG_LIGA = TTFHelper.composeTag("liga");//Standard Ligatures
	public static final int FEATURE_TAG_LJMO = TTFHelper.composeTag("ljmo");//Leading Jamo Forms
	public static final int FEATURE_TAG_LNUM = TTFHelper.composeTag("lnum");//Lining Figures
	public static final int FEATURE_TAG_LOCL = TTFHelper.composeTag("locl");//Localized Forms
	public static final int FEATURE_TAG_LTRA = TTFHelper.composeTag("ltra");//Left-to-right alternates
	public static final int FEATURE_TAG_LTRM = TTFHelper.composeTag("ltrm");//Left-to-right mirrored forms
	public static final int FEATURE_TAG_MARK = TTFHelper.composeTag("mark");//Mark Positioning
	public static final int FEATURE_TAG_MED2 = TTFHelper.composeTag("med2");//Medial Forms #2
	public static final int FEATURE_TAG_MEDI = TTFHelper.composeTag("medi");//Medial Forms
	public static final int FEATURE_TAG_MGRK = TTFHelper.composeTag("mgrk");//Mathematical Greek
	public static final int FEATURE_TAG_MKMK = TTFHelper.composeTag("mkmk");//Mark to Mark Positioning
	public static final int FEATURE_TAG_MSET = TTFHelper.composeTag("mset");//Mark Positioning via Substitution
	public static final int FEATURE_TAG_NALT = TTFHelper.composeTag("nalt");//Alternate Annotation Forms
	public static final int FEATURE_TAG_NLCK = TTFHelper.composeTag("nlck");//NLC Kanji Forms
	public static final int FEATURE_TAG_NUKT = TTFHelper.composeTag("nukt");//Nukta Forms
	public static final int FEATURE_TAG_NUMR = TTFHelper.composeTag("numr");//Numerators
	public static final int FEATURE_TAG_ONUM = TTFHelper.composeTag("onum");//Oldstyle Figures
	public static final int FEATURE_TAG_OPBD = TTFHelper.composeTag("opbd");//Optical Bounds
	public static final int FEATURE_TAG_ORDN = TTFHelper.composeTag("ordn");//Ordinals
	public static final int FEATURE_TAG_ORNM = TTFHelper.composeTag("ornm");//Ornaments
	public static final int FEATURE_TAG_PALT = TTFHelper.composeTag("palt");//Proportional Alternate Widths
	public static final int FEATURE_TAG_PCAP = TTFHelper.composeTag("pcap");//Petite Capitals
	public static final int FEATURE_TAG_PKNA = TTFHelper.composeTag("pkna");//Proportional Kana
	public static final int FEATURE_TAG_PNUM = TTFHelper.composeTag("pnum");//Proportional Figures
	public static final int FEATURE_TAG_PREF = TTFHelper.composeTag("pref");//Pre-Base Forms
	public static final int FEATURE_TAG_PRES = TTFHelper.composeTag("pres");//Pre-base Substitutions
	public static final int FEATURE_TAG_PSTF = TTFHelper.composeTag("pstf");//Post-base Forms
	public static final int FEATURE_TAG_PSTS = TTFHelper.composeTag("psts");//Post-base Substitutions
	public static final int FEATURE_TAG_PWID = TTFHelper.composeTag("pwid");//Proportional Widths
	public static final int FEATURE_TAG_QWID = TTFHelper.composeTag("qwid");//Quarter Widths
	public static final int FEATURE_TAG_RAND = TTFHelper.composeTag("rand");//Randomize
	public static final int FEATURE_TAG_RKRF = TTFHelper.composeTag("rkrf");//Rakar Forms
	public static final int FEATURE_TAG_RLIG = TTFHelper.composeTag("rlig");//Required Ligatures
	public static final int FEATURE_TAG_RPHF = TTFHelper.composeTag("rphf");//Reph Forms
	public static final int FEATURE_TAG_RTBD = TTFHelper.composeTag("rtbd");//Right Bounds
	public static final int FEATURE_TAG_RTLA = TTFHelper.composeTag("rtla");//Right-to-left alternates
	public static final int FEATURE_TAG_RTLM = TTFHelper.composeTag("rtlm");//Right-to-left mirrored forms
	public static final int FEATURE_TAG_RUBY = TTFHelper.composeTag("ruby");//Ruby Notation Forms
	public static final int FEATURE_TAG_SALT = TTFHelper.composeTag("salt");//Stylistic Alternates
	public static final int FEATURE_TAG_SINF = TTFHelper.composeTag("sinf");//Scientific Inferiors
	public static final int FEATURE_TAG_SIZE = TTFHelper.composeTag("size");//Optical size
	public static final int FEATURE_TAG_SMCP = TTFHelper.composeTag("smcp");//Small Capitals
	public static final int FEATURE_TAG_SMPL = TTFHelper.composeTag("smpl");//Simplified Forms
	public static final int FEATURE_TAG_SS01 = TTFHelper.composeTag("ss01");//Stylistic Set 1
	public static final int FEATURE_TAG_SS02 = TTFHelper.composeTag("ss02");//Stylistic Set 2
	public static final int FEATURE_TAG_SS03 = TTFHelper.composeTag("ss03");//Stylistic Set 3
	public static final int FEATURE_TAG_SS04 = TTFHelper.composeTag("ss04");//Stylistic Set 4
	public static final int FEATURE_TAG_SS05 = TTFHelper.composeTag("ss05");//Stylistic Set 5
	public static final int FEATURE_TAG_SS06 = TTFHelper.composeTag("ss06");//Stylistic Set 6
	public static final int FEATURE_TAG_SS07 = TTFHelper.composeTag("ss07");//Stylistic Set 7
	public static final int FEATURE_TAG_SS08 = TTFHelper.composeTag("ss08");//Stylistic Set 8
	public static final int FEATURE_TAG_SS09 = TTFHelper.composeTag("ss09");//Stylistic Set 9
	public static final int FEATURE_TAG_SS10 = TTFHelper.composeTag("ss10");//Stylistic Set 10
	public static final int FEATURE_TAG_SS11 = TTFHelper.composeTag("ss11");//Stylistic Set 11
	public static final int FEATURE_TAG_SS12 = TTFHelper.composeTag("ss12");//Stylistic Set 12
	public static final int FEATURE_TAG_SS13 = TTFHelper.composeTag("ss13");//Stylistic Set 13
	public static final int FEATURE_TAG_SS14 = TTFHelper.composeTag("ss14");//Stylistic Set 14
	public static final int FEATURE_TAG_SS15 = TTFHelper.composeTag("ss15");//Stylistic Set 15
	public static final int FEATURE_TAG_SS16 = TTFHelper.composeTag("ss16");//Stylistic Set 16
	public static final int FEATURE_TAG_SS17 = TTFHelper.composeTag("ss17");//Stylistic Set 17
	public static final int FEATURE_TAG_SS18 = TTFHelper.composeTag("ss18");//Stylistic Set 18
	public static final int FEATURE_TAG_SS19 = TTFHelper.composeTag("ss19");//Stylistic Set 19
	public static final int FEATURE_TAG_SS20 = TTFHelper.composeTag("ss20");//Stylistic Set 20
	public static final int FEATURE_TAG_SUBS = TTFHelper.composeTag("subs");//Subscript
	public static final int FEATURE_TAG_SUPS = TTFHelper.composeTag("sups");//Superscript
	public static final int FEATURE_TAG_SWSH = TTFHelper.composeTag("swsh");//Swash
	public static final int FEATURE_TAG_TITL = TTFHelper.composeTag("titl");//Titling
	public static final int FEATURE_TAG_TJMO = TTFHelper.composeTag("tjmo");//Trailing Jamo Forms
	public static final int FEATURE_TAG_TNAM = TTFHelper.composeTag("tnam");//Traditional Name Forms
	public static final int FEATURE_TAG_TNUM = TTFHelper.composeTag("tnum");//Tabular Figures
	public static final int FEATURE_TAG_TRAD = TTFHelper.composeTag("trad");//Traditional Forms
	public static final int FEATURE_TAG_TWID = TTFHelper.composeTag("twid");//Third Widths
	public static final int FEATURE_TAG_UNIC = TTFHelper.composeTag("unic");//Unicase
	public static final int FEATURE_TAG_VALT = TTFHelper.composeTag("valt");//Alternate Vertical Metrics
	public static final int FEATURE_TAG_VATU = TTFHelper.composeTag("vatu");//Vattu Variants
	public static final int FEATURE_TAG_VERT = TTFHelper.composeTag("vert");//Vertical Writing
	public static final int FEATURE_TAG_VHAL = TTFHelper.composeTag("vhal");//Alternate Vertical Half Metrics
	public static final int FEATURE_TAG_VJMO = TTFHelper.composeTag("vjmo");//Vowel Jamo Forms
	public static final int FEATURE_TAG_VKNA = TTFHelper.composeTag("vkna");//Vertical Kana Alternates
	public static final int FEATURE_TAG_VKRN = TTFHelper.composeTag("vkrn");//Vertical Kerning
	public static final int FEATURE_TAG_VPAL = TTFHelper.composeTag("vpal");//Proportional Alternate Vertical Metrics
	public static final int FEATURE_TAG_VRT2 = TTFHelper.composeTag("vrt2");//Vertical Alternates and Rotation
	public static final int FEATURE_TAG_ZERO = TTFHelper.composeTag("zero");//Slashed Zero
	
	private OTFTypography() {
		// prevent instance
	}
	
}
