package com.docscience.pathfinder.font.driver.type2;

import com.docscience.pathfinder.font.driver.cff.CFFFormatException;

/**
 * @author wxin
 *
 */
public class Type2CharStringException extends CFFFormatException {

    /**
     * Generated by Eclipse 3.2.1
     */
    private static final long serialVersionUID = 2054777309888133250L;

    public Type2CharStringException(String msg) {
        super(msg);
    }

}
