package com.docscience.pathfinder.font.driver.type1;

import com.docscience.pathfinder.font.driver.FontException;

/**
 * @author wxin
 *
 */
public class Type1CharStringException extends FontException {

    /**
     * Generated by Eclipse 3.2.1
     */
    private static final long serialVersionUID = -709001075546255532L;

    public Type1CharStringException(String msg) {
        super(msg);
    }

}

