package com.docscience.pathfinder.font.driver.ttf;

import java.io.IOException;

/**
 * @author wxin
 *
 */
public class TTFCMapEncodingFormat12 extends TTFCMapEncoding {
    
    /**
     * Generated by Eclipse 
     */
    private static final long serialVersionUID = 2480187927051402849L;

    @Override
	public int getFormat() {
        return CMAP_FORMAT_12;
    }
    
    @Override
	public int getGlyphID(int code) {
    	assert(false) : "not implement yet";
        return 0;
    }

    @Override
	public void read(long offset, TTFRandomReader rd)
            throws TTFFormatException, IOException {
    	assert(false) : "not implement yet";
    }

    @Override
	public int getFirstChar() {
    	assert(false) : "not implement yet";
    	return 0;
    }

    @Override
	public int getLastChar() {
    	assert(false) : "not implement yet";
        return 0;
    }

}
