package com.docscience.pathfinder.font.driver.ttf;

/**
 * @author wxin
 *
 */
public class TTFFormatException extends TTFException {

    /**
     * Generated by Eclipse 3.2.1
     */
    private static final long serialVersionUID = -8897949576360905037L;

    public TTFFormatException(String msg, long pos) {
        super(msg + " at " + Long.toString(pos));
    }

    public TTFFormatException(String msg) {
        super(msg);
    }
}
