package com.docscience.pathfinder.font.driver.ttf;

public class TTFGlyphException extends TTFFormatException {

    /**
     * Generated by Eclipse 3.2.1
     */
    private static final long serialVersionUID = -2774851959447324410L;

    public TTFGlyphException(String msg) {
        super(msg);
    }
    
}
